.htpasswd, Dockerfile, nginx.conf
We have configured a Dockerfile so that a front-end image can be created with the http encrypt password feature, which allows you to request an authentication before accessing the application.
=> feat: Dockerfile added

.github/workflows/build.yml, iac/deploy_dev.yml, iac/hosts.yml
=> Setup Continuous integration

src/app/components/footer/footer.component.html, src/app/components/footer/footer.component.ts
This PR is for displaying shop on the footer instead of displaying dummy shops
=> fix:Displaying real shops on footer

src/app/pages/products/product-result/product-result.component.html, src/app/pages/products/product-result/product-result.component.scss, src/app/pages/products/product-result/product-result.component.ts
This PR is for displaying real product rating instead of static.
=> fix:Fixing the product rating to be dynanic from database

src/app/pages/products/product-detail/product-detail.component.html
This PR is about to fix the sharing icons redirection in product detail.
=> fix:Fixing the redirections on product detail

src/app/components/footer/footer.component.html, src/app/components/footer/footer.component.ts, src/app/pages/stores/list-store/stores.component.html, src/app/pages/stores/list-store/stores.component.ts
This PR is to hide the action button in the shop list page and also display more button in the footer while the number shop  extends 5
=> fix:Hiding action buttons in list shop

src/app/pages/products/product-result/product-result.component.html, src/app/pages/products/product-result/product-result.component.scss, src/app/pages/products/product-result/product-result.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json, src/environments/environment.ts
[vaana-737](https://tree.taiga.io/project/thierrymonthe-vaana_tech/task/737)
=> view for wrong search

src/app/models/products/products.ts, src/app/models/review/review.spec.ts, src/app/models/review/review.ts
review service [vaana-738](https://tree.taiga.io/project/thierrymonthe-vaana_tech/task/738)
=> review service

src/app/pages/stores/list-store/stores.component.html, src/app/pages/stores/list-store/stores.component.scss, src/app/pages/stores/list-store/stores.component.ts, src/app/pages/stores/store-products/store-products.component.html, src/app/pages/stores/store-products/store-products.component.scss, src/app/pages/stores/store-products/store-products.component.ts
[vaana-746](https://tree.taiga.io/project/thierrymonthe-vaana_tech/task/746)
=> list a store reviews

src/app/app.module.ts, src/app/components/products/products.component.html, src/app/components/products/products.component.ts, src/app/pages/products/product-detail/product-detail.component.html, src/app/pages/products/product-detail/product-detail.component.ts, src/app/pages/stores/store-products/store-products.component.html, src/app/pages/stores/store-products/store-products.component.scss, src/app/pages/stores/store-products/store-products.component.ts, src/app/pages/stores/store-review/store-review/store-review.component.css, src/app/pages/stores/store-review/store-review/store-review.component.html, src/app/pages/stores/store-review/store-review/store-review.component.spec.ts, src/app/pages/stores/store-review/store-review/store-review.component.ts, src/app/pages/stores/store-review/update-store-review/update-store-review.component.html, src/app/pages/stores/store-review/update-store-review/update-store-review.component.spec.ts, src/app/pages/stores/store-review/update-store-review/update-store-review.component.ts, src/environments/environment.ts
vaana [747 ](https://tree.taiga.io/project/thierrymonthe-vaana_tech/task/747)[748 ](https://tree.taiga.io/project/thierrymonthe-vaana_tech/task/748)[749](749)
=> Store review

src/app/pages/checkout/checkout.component.ts, src/app/pages/products/create-product/create-product.component.html, src/app/pages/products/products.component.html, src/app/pages/products/update-product/update-product.component.html, src/app/pages/products/update-product/update-product.component.ts, src/app/pages/stores/list-store/stores.component.html, src/app/pages/stores/list-store/stores.component.ts
=> active store bug correction

src/app/pages/categories/categories.component.html, src/app/pages/categories/categories.component.ts, src/app/pages/categories/create-categories/create-categories.component.html, src/app/pages/categories/create-categories/create-categories.component.ts, src/app/pages/categories/update-categories/update-categories.component.ts, src/app/pages/category-page/category-page.component.html
=> add image to category page

src/app/components/products/products.component.html, src/app/pages/cart/cart.component.ts, src/app/pages/order/order-details/order-details.component.html, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json
=> correction of bugs

src/app/components/buyer/buyer-navbar/buyer-navbar.component.html, src/app/components/footer/footer.component.html, src/app/components/headers/headers.component.html, src/app/components/shared/search-bar/search-bar.component.html, src/app/pages/components/regions/regions.component.html, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json
translate header navbar and footer
=> translate header navbar and footer

src/app/pages/wishlist/wishlist.component.html, src/app/pages/wishlist/wishlist.component.ts
- set the stock for the wishlist
- -no dependency added
=> fix: wishlist stock

src/app/components/buyer/buyer-navbar/buyer-navbar.component.html, src/app/components/buyer/buyer-navbar/buyer-navbar.component.scss, src/app/components/buyer/buyer-navbar/buyer-navbar.component.ts, src/app/components/headers/headers.component.html
- fixed category parents in hamburger menu
- no dependency added
=> fix: category parents in hamburger menu

src/app/pages/wishlist/wishlist.component.html, src/app/pages/wishlist/wishlist.component.ts
- I implemented the confirmation of deletion
=> fix: wishlis confirmation of deletion

src/app/pages/cart/cart.component.html, src/app/pages/cart/cart.component.scss
I changed the style of the "go to home" button from the cart page.
=> style of go to shop button from cart page

src/app/components/headers/headers.component.html, src/app/components/headers/headers.component.scss
I fixed the behavior of call to action on mobile.
=> Fix call to action display on mobile

src/app/app.module.ts, src/app/components/reload-route/reload-route.component.html, src/app/components/reload-route/reload-route.component.spec.ts, src/app/components/reload-route/reload-route.component.ts
I fixed the reloading component from store page
- no dependency added 
- 1 component created 
- file updeted (app-module)
=> fix: reloading component

src/app/components/review-item/review-item.component.html, src/app/components/review-item/review-item.component.ts, src/app/components/reviews-stats/reviews-stats.component.html, src/app/pages/cart/cart.component.scss, src/app/pages/wishlist/wishlist.component.html, src/app/pages/wishlist/wishlist.component.ts
I  fixed !
- remove a product from the wishlist after adding them to the cart
- reviewer deletion confirm
=> fix: wishlist bug, and reviewer deletion confirm

src/app/app-routing.module.ts, src/app/pages/cart/cart.component.scss, src/app/pages/products/product-result/product-result.component.html, src/app/pages/user/registration/registration.component.ts
- I have correct the errors reported by fabrice
=> correct the errors reported by fabrice 

src/app/pages/components/signup/signup.component.html, src/styles.scss
I integrated the new ui of the login/registion section.
=> Feature/new UI login section

src/app/components/footer/footer.component.html, src/app/components/footer/footer.component.ts, src/app/models/newsletter/newsletter.spec.ts, src/app/models/newsletter/newsletter.ts, src/app/services/newsletter/newsletter.service.spec.ts, src/app/services/newsletter/newsletter.service.ts
[vaana-893](https://tree.taiga.io/project/thierrymonthe-vaana_tech/task/893)
Add newsletter model, service and call post endpoint
=> newsletter feature

src/app/app.component.html, src/app/components/buyer/buyer-navbar/buyer-navbar.component.ts, src/app/components/footer/footer.component.html, src/app/components/footer/footer.component.ts, src/app/components/products/products.component.html, src/app/pages/cart/cart.component.html, src/app/pages/category-page/categoy-detail/categoy-detail.component.html, src/app/pages/category-page/categoy-detail/categoy-detail.component.ts, src/app/pages/components/best-deals/best-deals.component.html, src/app/pages/user/profile/profile.component.ts
Fixed bugs related to the link
=> fix:  link

.github/workflows/build.yml
add codeQL analyze in pipeline CI
=> add codeQL analyze in pipeline CI

iac/deploy_dev.yml, iac/hosts.yml
=> update ip host to deploy

src/app/app.module.ts, src/app/pages/categories/create-categories/create-categories.component.ts, src/app/shared/shared.module.ts
=> resolve merge conflict

src/app/pages/checkout/checkout.component.html
=> update checkout component

src/app/app.component.ts, src/app/components/products/products.component.ts, src/app/components/shipping-adress/shipping-adress.component.html, src/app/components/shipping-adress/shipping-adress.component.ts, src/app/dtos/order/shipping-address.ts, src/app/models/parcel/parcel.ts, src/app/models/payment/bank-account.ts, src/app/models/shipping-address/shipping-address.ts, src/app/pages/checkout/checkout.component.html, src/app/pages/checkout/checkout.component.ts, src/app/pages/products/create-product/create-product.component.html, src/app/pages/products/create-product/create-product.component.ts, src/app/services/products/products.service.ts, src/app/services/shipping-adress/shipping-adress.service.spec.ts, src/app/services/shipping-adress/shipping-adress.service.ts, src/assets/i18n/en.json, src/environments/environment.ts
I add shipping adress for the checkout.
=> Adding shipping adress for the checkout

src/app/pages/products/create-product/create-product.component.html, src/app/pages/products/create-product/create-product.component.scss
I changed the ui of add product form.
=> Adding new add product form

src/app/app.component.ts, src/app/app.module.ts, src/app/components/shipping-adress/shipping-adress.component.ts, src/app/models/payment/bank-account.ts, src/app/models/payment/credit-card.ts, src/app/models/shipping-address/shipping-address.ts, src/app/pages/cart/cart.component.html, src/app/pages/cart/cart.component.scss, src/app/pages/cart/cart.component.ts, src/app/pages/checkout/checkout.component.html, src/app/pages/checkout/checkout.component.scss, src/app/pages/checkout/checkout.component.ts, src/app/pages/products/create-product/create-product.component.ts, src/app/pages/products/product-detail/product-detail.component.html, src/app/pages/products/products.component.ts, src/app/pages/wishlist/wishlist.component.html, src/app/services/cart/cart.service.ts, src/app/services/orders/order-items.service.ts, src/app/services/orders/orders.service.ts, src/app/services/payment/payment.service.ts
I added some feature for the checkout.
=> Some feature for checkout
